name: Doc Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        - run: sudo apt-get update && sudo apt-get install -y docutils-common
        - run: python setup.py --long-description | rst2html --strict --no-raw > /dev/null
        - run: pip install -e .
        - run: python -m doctest README.rst
